### ISSUE TITLE
Expect partition-id-expression to be a String instead of Integer in spring-integration-kafka-2.0.xsd

### ISSUE THREAD

**Issue by rchzzjcn** [spring-projects/spring-integration-kafka#135]
I am using XML to configure as below:
```xml
<int-kafka:outbound-channel-adapter id="kafkaOutboundChannelAdapter"
                                        kafka-template="testKafkaTemplate"
                                        auto-startup="true"
                                        channel="testInputToKafkaChannel"

                                        topic-expression="headers.topic == null ? 'test.topic' : headers.topic"
                                        partition-id-expression="headers.partitionId == null ? '0' : headers.partitionId"
                                        message-key-expression="headers.messageKey == null ? '0' : headers.messageKey"
                                        >
    </int-kafka:outbound-channel-adapter>
```

But it fails to start with the following error:
```
Caused by: org.xml.sax.SAXParseException; lineNumber: 35; columnNumber: 42; cvc-datatype-valid.1.2.1: 'headers.partitionId == null ? '0' : headers.partitionId' is not a valid value for 'integer'.
```

According to the log, it seems that partition-id-expression seems to be a String instead of Integer in spring-integration-kafka-2.0.xsd:
```
			<xsd:attribute name="partition-id-expression" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation><![CDATA[
								Specifies the expression to determine the partition for Kafka message
								against the Message at runtime.
								This attribute is mutually exclusive with 'partition-id' attribute.
							]]></xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
```

**Comment by artembilan** [comment]
The attribute with `integer` type has been introduced since Spring Integration Kafka 1.2: https://github.com/spring-projects/spring-integration-kafka/commit/0a34e540c6788a1d7d0609e7f73664f354cc56ae#diff-2da9c1031c8b469abf41f7c321984a95.

Strange, looks like no body uses XML configuration since there, because it really fail when I just use `'2'` :smile: .
Although I always thought that it is an advice only for IDE to have those types for attributes, but yeah, it fails starting:
```
Caused by: org.xml.sax.SAXParseException; lineNumber: 21; columnNumber: 58; cvc-datatype-valid.1.2.1: 'headers.my_partition' is not a valid value for 'integer'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processOneAttribute(XMLSchemaValidator.java:2825)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processAttributes(XMLSchemaValidator.java:2762)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2050)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:429)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
```

Thank you for catching and reporting that!
