### ISSUE TITLE
JSON deserialization problem

### ISSUE THREAD

**Issue by tomvandenberge** [spring-projects/spring-integration-kafka#147]
I'm trying to send messages to Kafka, while serializing them to JSON using the JsonSerializer, and then receive them while deserializing them using the JsonDeserializer. All configuration is in XML.

Serialization to JSON, sending to and receiving from Kafka works fine, but the deserialization from JSON to the correct object fails with a `java.lang.IllegalArgumentException: Unrecognized Type: [null]` exception.

The full configuration for both sending and receiving:
```
	<channel id="inputToKafka"/>
	<channel id="outputFromKafka"/>

	<int-kafka:outbound-channel-adapter id="kafkaOutbound"
		kafka-template="kafkaTemplate"
		channel="inputToKafka"
		topic="fubar">
	</int-kafka:outbound-channel-adapter>

	<beans:bean id="stringJsonMessageConverter" class="org.springframework.kafka.support.converter.StringJsonMessageConverter"/>

	<beans:bean id="kafkaTemplate" class="org.springframework.kafka.core.KafkaTemplate">
		<beans:constructor-arg>
			<beans:bean class="org.springframework.kafka.core.DefaultKafkaProducerFactory">
				<beans:constructor-arg>
					<beans:map>
						<beans:entry key="bootstrap.servers" value="localhost:9092" />
						<beans:entry key="key.serializer" value="org.apache.kafka.common.serialization.StringSerializer" />
                    	<beans:entry key="value.serializer" value="org.springframework.kafka.support.serializer.JsonSerializer" />
					</beans:map>
				</beans:constructor-arg>
			</beans:bean>
		</beans:constructor-arg>
		<beans:property name="messageConverter" ref="stringJsonMessageConverter"/>
	</beans:bean>
	
	<int-kafka:message-driven-channel-adapter
        id="kafkaListener"
        listener-container="container1"
        auto-startup="true"
        channel="outputFromKafka"
        message-converter="stringJsonMessageConverter"/>

	<beans:bean id="container1" class="org.springframework.kafka.listener.KafkaMessageListenerContainer">
	    <beans:constructor-arg>
	        <beans:bean class="org.springframework.kafka.core.DefaultKafkaConsumerFactory">
	            <beans:constructor-arg>
	                <beans:map>
	                	<beans:entry key="bootstrap.servers" value="localhost:9092" />
						<beans:entry key="key.deserializer" value="org.apache.kafka.common.serialization.StringDeserializer" />
                    	<!-- <beans:entry key="value.deserializer" value="org.springframework.kafka.support.serializer.JsonDeserializer"/>-->
                    	<beans:entry key="group.id" value="mygroup" />
	                </beans:map>
	            </beans:constructor-arg>
	            <beans:property name="valueDeserializer">
	            	<beans:bean class="org.springframework.kafka.support.serializer.JsonDeserializer">
	            		<beans:constructor-arg value="com.drillster.KafkaTest.MyMessage"/>
	            	</beans:bean>
	            </beans:property>
	        </beans:bean>
	    </beans:constructor-arg>
	    <beans:constructor-arg>
	    	<beans:bean class="org.springframework.kafka.listener.config.ContainerProperties">
			    <beans:constructor-arg name="topics" value="fubar" />
	    	</beans:bean>
	    </beans:constructor-arg>
	</beans:bean>
```

When the received JSON is deserialized, this exception is thrown:
```
java.lang.IllegalArgumentException: Unrecognized Type: [null]
	at com.fasterxml.jackson.databind.type.TypeFactory._constructType(TypeFactory.java:517)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:466)
	at org.springframework.kafka.support.converter.StringJsonMessageConverter.extractAndConvertValue(StringJsonMessageConverter.java:75)
	at org.springframework.kafka.support.converter.MessagingMessageConverter.toMessage(MessagingMessageConverter.java:82)
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.toMessagingMessage(MessagingMessageListenerAdapter.java:135)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:287)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:279)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:761)
...
```
Some investigation shows that the `MessagingMessageListenerAdapter` that is used is set up without an expected message payload type (`inferredType`), which leads to this exception. I couldn't find a way to configure this though.

Any help is much appreciated!

**Comment by garyrussell** [comment]
Since you are using the JSON (de)serializer, you should not be also using a `StringJsonMessageConverter` - you are effectively doing double JSON conversion.

If you remove the `StringJsonMessageConverter` from the template and message-driven adapter, you should be ok.

It does appear, however, that the `StringJsonMessageConverter` is not compatible with the Spring Integration adapter (due to that inferred type stuff). It was designed for use with the `@KafkaListener`. We should address that - at least giving a more meaningful error.

See [these samples from Spring One](https://github.com/SpringOnePlatform2016/grussell-spring-kafka). It discusses the use of the (de)serializers Vs. the converters (when using `@KafkaListener`).

**Comment by garyrussell** [comment]
We should provide a mechanism to pass an inferred type to the `StringJsonMessageConverter`.

**Comment by tomvandenberge** [comment]
Leaving out the `StringJsonMessageConverter` does the trick -- thanks!

The reference manual (3.1.3) lead to believe I needed to use both, specifically because of the sentence "...it is not enough on the Messaging level...".

**Comment by garyrussell** [comment]
Thanks; I'll polish up the docs.
