### ISSUE TITLE
NoClassDefFoundError during Shutdown

### ISSUE THREAD

**Issue by yohanliyanage** [spring-projects/spring-integration-kafka#60]
I have a Spring Boot application that uses 1.2.1 of Kafka Integration. I see the following exception when the application shuts down. Commons Lang 2.5 is already in the classpath and I don't get any errors during start up.
```
2015-09-02 18:28:31.431 ERROR 10672 --- [       Thread-1] [                                    ] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name '(inner bean)#1ea930eb#1' threw an exception

java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/HashCodeBuilder
	at org.springframework.integration.kafka.support.ProducerMetadata.hashCode(ProducerMetadata.java:117)
	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessBeforeDestruction(PersistenceAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:239)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:900)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:589)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:900)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:589)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:900)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:589)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:900)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:907)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:884)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:150)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:804)
```

**Comment by garyrussell** [comment]
My best guess is that the class was not loaded during normal processing (it's used to calculate the hashcode for the `ProducerMetadata`).

The context is being shut down (on the shutdown hook). The JPA code unconditionally tries to remove the bean from the entity manager map, which needs to calculate the hashcode. Since we're shutting down, the JVM won't load the class.

You could try working around it by forcing the class to be loaded, by adding...

    HashCodeBuilder.reflectionHashCode("foo");

to your application.

**Comment by garyrussell** [comment]
I tried to reproduce this with a test case, and even though it's called from the shutdown hook, the class was successfully loaded for me...

    [Loaded org.apache.commons.lang.builder.HashCodeBuilder from file:/Users/.../.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.6/ce1edb914c94ebc388f086c6827e8bdeec71ac2/commons-lang-2.6.jar]

**Comment by artembilan** [comment]
Having `commons-lang` as a transitive artifact for the `optional` `avro` artifact, I'd prefere to get rid of this `HashCodeBuilder` usage and other similar throughout the project.

Looks like you have several `ClassLoader` in your app and `ProducerMetadata` and `HashCodeBuilder` are loaded by different `ClassLoader`s. 
Since `HashCodeBuilder.reflectionHashCode` is static method its class is really loaded on demand.

That's why we hack Java 8 usage from the Java 6 environment (or the optional dependencies) with the wrapper classes.

As I said: it would be better to get rid of the `optional` usage from such core components like `ProducerMetadata`.

**Comment by garyrussell** [comment]
@artembilan - I don't think the hashcode should be calculated here anyway - it will change if fields are modified and thus won't be found if it's used as a key to a hash.

**Comment by garyrussell** [comment]
We should talk to @ghillert to see why he used it.

**Comment by artembilan** [comment]
After some internal discussion we realized that `equals()` and `hashCode()` are redundant for the `ProducerMetadata` and similar `ProducerConfiguration`.

**Comment by artembilan** [comment]
PullRequest on the matter #61

**Comment by yohanliyanage** [comment]
Thanks for the very quick response guys.
